# 第五章语句
## 5.1 简单语句
```
ival+5;//这样的语句叫做表达式语句(无用的表达式语句)
求出结果丢掉

; //空语句
空语句
while(xxx); 这里使用了 ;空语句
```
#### 别漏写分号也别多写分号
#### 复合语句(块)
```
{ 
  作用域  
};称为块

note:
块不以;作为结尾
```
## 5.2 语句作用域
## 5.3 条件语句
### 5.3.2
```cpp
switch(xx){
    case 必须是整形常量：
    case 必须是整形常量：
        char int short long long 
        break;

}

note:
 char c = 'c';

    switch (c)
    {
    case 'c':
        cout << "c" << endl;
    case 'g':
        cout << "c" << endl;
    }
//print
c
c
当第一个匹配并且没有break,则会执行后面的所有语句

```
#### default 标签
```
如果没有任何于case 匹配上 程序会执行 default

```
#### switch 内部变量定义
```
//c++ 这种情况下是允许的  ii 定义未初始化  
    case 'c':
        int ii;
        string cc;//cc会调用默认初始化语句所以也不行 即使 cc在 case 'g' 不使用
        break;
    case 'g':
        ii=200;
        cout << ii << endl;
        cout << cc << endl;
        break;
    }

//c++ 不允许 编译报错 ii 跨过变量的初始化语句
    case 'c':
        int ii=300;
        break;
    case 'g':
        ii=200;
        cout << ii << endl;
        break;
    }


case xx:{
    里面可以定义任意对象
    break;
}
```

## 5.6 try 语句和异常处理
```
1.throw 异常检查部分使用throw 来表示遇到无法解决的问题
2.try block:
  异常处理部分 
  try{

  }catch(e){
    异常处理部分
  }catch(e2){
    异常处理部分
  }
3.一套异常类 用于 从 throw 到 catch 之间传递信息的类
```
### 5.6.1 throw 表达式
```cpp
throw 抛出的异常类型

抛出异常将终止程序,使程序不在继续向下面执行
会将执行权交给catch 执行处理异常的代码


#include<stdexcept>
runtime_error 类
```
### 5.6.2 try语句
```cpp
try{

}catch(exception){
    handle-exception-statements
}catch(exception){
    handle-exception-statements
}


```